### ISSUE TITLE
couldn't read `src\../driver/driver_uefi.dll`

### ISSUE THREAD

**Issue by auyylaso** [Valthrun/valthrun-uefi-mapper#2]
Where can I find this DLL? I looked through your whole Github organization and couldn't find this DLL to compile the UEFI driver mapper. Do I need to supply my own Driver. If so I can probably figure out how to make my own from the mapper code that's here.

**Comment by WolverinDEV** [comment]
Hey,  
good question actually.  
  
The Valthrun UEFI mapper compatible driver is just a build artefact of the private Valthrun driver repository.  
I've attached the latest `driver_uefi.dll` to this message: [driver_uefi.zip](https://github.com/Valthrun/valthrun-uefi-mapper/files/15122941/driver_uefi.zip)

PS: Yes you could create your own driver as well and use this with this mapper.  
But you'll have to keep the few caveats in mind mentioned here:  
https://github.com/Valthrun/valthrun-uefi-mapper/blob/master/src/main.rs#L688 (Note: currently all sections are mapped)  
  
Additionally no external imports are being resolved.  
This will most likely be the biggest issue for out of the box drivers :)

**Comment by auyylaso** [comment]
I figured it wouldn't be easy to make my own driver using your mapper from what I saw this is a really well put together Driver and project all around! But thank you for the zip
